[model]
training = true
in_channels = 1
input_size = [32, 1, 28, 28]
filters = 48
units1 = 80
units2 = 72

[types]
training = "bool"
in_channels = "int"
input_size = "tuple"
filters = "int"
units1 = "int"
units2 = "int"
